repos:
  # Code formatting
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.9
        files: ^(src|tests)/.*\.py$

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: ^(src|tests)/.*\.py$

  # Linting
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ["--max-line-length=88", "--extend-ignore=E203,W503"]
        files: ^(src|tests)/.*\.py$

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        args: ["--ignore-missing-imports"]
        files: ^src/.*\.py$

  # General code quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Remove trailing whitespace
      - id: trailing-whitespace
        exclude: ^.*\.(md|rst)$
      # Ensure files end with newline
      - id: end-of-file-fixer
        exclude: ^.*\.(md|rst)$
      # Check for large files
      - id: check-added-large-files
        args: ['--maxkb=10000']  # 10MB limit
      # Check for merge conflicts
      - id: check-merge-conflict
      # Check YAML syntax
      - id: check-yaml
        files: \.(yaml|yml)$
      # Check JSON syntax
      - id: check-json
        files: \.json$
      # Check Python AST
      - id: check-ast
        files: \.py$
      # Check for secrets
      - id: detect-private-key

  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-r", "src/", "-f", "json"]
        files: ^src/.*\.py$

  # Terraform formatting
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5
    hooks:
      - id: terraform_fmt
        files: \.tf$
      - id: terraform_validate
        files: \.tf$

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        files: Dockerfile.*

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        files: \.md$
        args: ["--disable", "MD013", "MD033", "MD041"]

# CI configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false 