version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - ENV=development
    volumes:
      - ./data:/app/data:ro  # Mount data as read-only
      - ./src:/app/src       # Mount source for development
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - ml-network

networks:
  ml-network:
    driver: bridge 